<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bal" nsURI="http://www.example.org/bal" nsPrefix="bal">
  <eClassifiers xsi:type="ecore:EClass" name="BAL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" lowerBound="1"
        eType="#//Library" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1"
        eType="#//Members" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1"
        eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="articles" upperBound="-1"
        eType="#//Article" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//Book" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borrowedBooks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classlevels" upperBound="-1"
        eType="#//ClassLevel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjects" upperBound="-1"
        eType="#//Subject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//Book"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parent" eSuperTypes="#//User"/>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
        eType="#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" upperBound="2"
        eType="#//Parent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payments" upperBound="-1"
        eType="#//Payment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Members">
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandlines" upperBound="-1"
        eType="#//CommandLine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDelivred" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="article" eType="#//Article"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Book"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Article">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" eType="#//Command"/>
  </eClassifiers>
</ecore:EPackage>
