<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bstrap" nsURI="http://www.example.org/bstrap" nsPrefix="bstrap">
  <eClassifiers xsi:type="ecore:EClass" name="SiteRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//TextElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Link"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOutline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpinner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBlockButton" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ButtonGroup" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buttons" upperBound="-1"
        eType="#//Button" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navbar" eSuperTypes="#//TextElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imageBrand" eType="#//Image"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//TextElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imgSrc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Title" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//TextElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecondaryButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuccessButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="WarningButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="DarkButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="LightButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="DangerButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeLine" eSuperTypes="#//TextElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeBlock" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codelines" upperBound="-1"
        eType="#//CodeLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoldText" eSuperTypes="#//Text"/>
  <eClassifiers xsi:type="ecore:EClass" name="ItalicText" eSuperTypes="#//Text"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedList" eSuperTypes="#//List"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedList" eSuperTypes="#//List"/>
  <eClassifiers xsi:type="ecore:EClass" name="List" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listElements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockQuote" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quotes" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Code" eSuperTypes="#//TextElement"/>
</ecore:EPackage>
